//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrBeshoyClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineDetail
    {
        public int Id { get; set; }
        public int MedicineId { get; set; }
        public int TreatmentId { get; set; }
        public int TreatmentPeriodId { get; set; }
        public int TreatmentDescriptionId { get; set; }
    
        public virtual Medicine Medicine { get; set; }
        public virtual TreatmentDescription TreatmentDescription { get; set; }
        public virtual TreatmentPeriod TreatmentPeriod { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
