//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrBeshoyClinic.DAL.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrBeshoyClinicEntities : DbContext
    {
        public DrBeshoyClinicEntities()
            : base("name=DrBeshoyClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChronicDiseas> ChronicDiseases { get; set; }
        public virtual DbSet<DrugHx> DrugHxes { get; set; }
        public virtual DbSet<EmgNcv> EmgNcvs { get; set; }
        public virtual DbSet<ExaminationChronicDisease> ExaminationChronicDiseases { get; set; }
        public virtual DbSet<Examination> Examinations { get; set; }
        public virtual DbSet<FamilyHx> FamilyHxes { get; set; }
        public virtual DbSet<LabTest> LabTests { get; set; }
        public virtual DbSet<MedicineDetail> MedicineDetails { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<Photo> Photos { get; set; }
        public virtual DbSet<Radiology> Radiologies { get; set; }
        public virtual DbSet<SurgicalHx> SurgicalHxes { get; set; }
        public virtual DbSet<TreatmentDescription> TreatmentDescriptions { get; set; }
        public virtual DbSet<TreatmentPeriod> TreatmentPeriods { get; set; }
        public virtual DbSet<Treatment> Treatments { get; set; }
    }
}
