//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrBeshoyClinic.DAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        public int Id { get; set; }
        public string PatientId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string OperativeDetails { get; set; }
        public string FuturePlan { get; set; }
        public string Approach { get; set; }
        public string Anesthesiologist { get; set; }
        public string Anesthesia { get; set; }
        public string Position { get; set; }
        public string Antibiotic { get; set; }
        public string BloodLoss { get; set; }
        public string ImplantUsed { get; set; }
        public string ImplantCompany { get; set; }
        public string Nurse { get; set; }
        public string Assisstant1 { get; set; }
        public string Assisstant2 { get; set; }
        public string Surgion { get; set; }
        public string Notes { get; set; }
        public bool IsCultureAndSensitivity { get; set; }
        public bool IsBiopsy { get; set; }
        public System.TimeSpan Start { get; set; }
        public System.TimeSpan End { get; set; }
        public System.TimeSpan Pressure { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
