USE DrBeshoyClinic
GO
ALTER TABLE ChronicDiseases ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Complaints ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Diagnosis ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE DrugHx ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE EmgNcv ALTER COLUMN Emg NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE EmgNcv ALTER COLUMN Ncv NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Examinations ALTER COLUMN ExaminationOfExamination NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE FamilyHx ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE LabTests ALTER COLUMN TestName NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE LabTests ALTER COLUMN TestResult NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Patients ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Patients ALTER COLUMN Address NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Patients ALTER COLUMN Phone NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Patients ALTER COLUMN Job NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE PostOperativeInstructions ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE PostOperativeTreatments ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Radiologies ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Radiologies ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE SurgicalHx ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE TreatmentDescriptions ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE TreatmentPeriods ALTER COLUMN Description NVARCHAR(MAX) NOT NULL
GO
ALTER TABLE Treatments ALTER COLUMN Name NVARCHAR(MAX) NOT NULL
GO